name: lms-client

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd /root/web-app/lms.client
            git pull origin main
            docker build -t lms-client .
            docker stop lms-client || true
            docker rm lms-client || true
            docker run -d -p 3000:3000 --name lms-client lms-client
